[world]
kind = "WorldContract"
class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
original_class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x3bcf0822c097dfee352c9c79763d1c6ad9aedc28c41dc79c1bda7235379dd48"
transaction_hash = "0x5baf42b18019f00c98021c0b4cd0c62da425a278c6d44f7ab3a03c5be0b4610"
block_number = 3
seed = "dojo_starter_chess"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x37384c69a08c6c153ba5e40375b0c073f1afcd2c85914116ac7a24f12858489"
class_hash = "0x553b1db012156889c2521686313f0a2903fe286f09c18cfebcfbd84abf0e1a9"
original_class_hash = "0x553b1db012156889c2521686313f0a2903fe286f09c18cfebcfbd84abf0e1a9"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_starter_chess-actions-4deba942.json"
reads = []
writes = [
    "dojo_starter_chess-Game",
    "dojo_starter_chess-Player",
]
init_calldata = []
tag = "dojo_starter_chess-actions"
systems = [
    "join",
    "move",
]
manifest_name = "dojo_starter_chess-actions-4deba942"

[[models]]
kind = "DojoModel"
class_hash = "0x37f4f37680914f11d2c9964cc0dc2a8c1e1cb045e2248f8cbff65d67aff3277"
original_class_hash = "0x37f4f37680914f11d2c9964cc0dc2a8c1e1cb045e2248f8cbff65d67aff3277"
abi = "manifests/dev/deployment/abis/models/dojo_starter_chess-Game-1be33659.json"
tag = "dojo_starter_chess-Game"
manifest_name = "dojo_starter_chess-Game-1be33659"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "color"
type = "u8"
key = false

[[models.members]]
name = "whites"
type = "u64"
key = false

[[models.members]]
name = "blacks"
type = "u64"
key = false

[[models.members]]
name = "pieces"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xf04df56f955e652a44f0c37fdc4c063e05c25d9070e267c2fa17682726aa5c"
original_class_hash = "0xf04df56f955e652a44f0c37fdc4c063e05c25d9070e267c2fa17682726aa5c"
abi = "manifests/dev/deployment/abis/models/dojo_starter_chess-Player-5c4e436c.json"
tag = "dojo_starter_chess-Player"
manifest_name = "dojo_starter_chess-Player-5c4e436c"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "color"
type = "u8"
key = true

[[models.members]]
name = "id"
type = "felt252"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false
